# Copy this file into the following folder:
#    Linux: /etc/newrelic-infra/integrations.d
#    Windows: C:\Program Files\New Relic\newrelic-infra\integrations.d
#
# For a complete description of the Configuration File Specification, please
# refer to the Integrations SDK documentation:
# https://docs.newrelic.com/docs/integrations/integrations-sdk/file-specifications

integration_name: com.newrelic.oracledb

instances:
  - name: oracledb-inventory
    command: inventory
    arguments: 
        extended_metrics: true
        username: username
        password: password
        hostname: oracle-host
        is_sys_dba: true
        service_name: oracle-service
  - name: oracledb-metrics
    command: metrics
    arguments: 
        extended_metrics: true
        username: username 
        password: password
        hostname: oracle-host
        is_sys_dba: true
        service_name: oracle-service
